stability.api.base-url=https://api.stability.ai
stability.api.key= ${STABILITY_API_KEY}

#Feign client configuration to handle multipart/form-data requests
feign.encode.encoder-class=org.springframework.openfeign.support.SpringEncoder
server.port=8081

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB